import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/molecules/navbar";
import styles from "../../styles/Home.module.css";

// import Swiper core and required modules
import SwiperCore, {
  Navigation,
  Pagination,
  Scrollbar,
  A11y,
  Autoplay,
} from "swiper";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

export default function Home() {
  const [activeCrew, SetActiveCrew] = React.useState(2);
  SwiperCore.use([Autoplay]);

  const crews = [
    {
      key: 1,
      crewName: "Douglas Hurley",
      role: "Commander",
      image: "/static/assets/crew/image-douglas-hurley.webp",
      content:
        "Douglas Gerald Hurley is an American engineer, former Marine Corps pilot and former NASA astronaut. He launched into space for the third time as commander of Crew Dragon Demo-2.",
    },
    {
      key: 2,
      crewName: "Douglas Hurley",
      role: "Mission Specialist",
      image: "/static/assets/crew/image-mark-shuttleworth.png",
      content:
        "Mark Richard Shuttleworth is the founder and CEO of Canonical, the company behind the Linux-based Ubuntu operating system. Shuttleworth became the first South African to travel to space as a space tourist.",
      avgDistance: "225 MIL. km",
      travelTime: "9 months",
    },
    {
      key: 3,
      crewName: "Victor Glover",
      role: "Pilot",
      image: "/static/assets/crew/image-victor-glover.png",
      content:
        "Pilot on the first operational flight of the SpaceX Crew Dragon to the International Space Station. Glover is a commander in the U.S. Navy where he pilots an F/A-18.He was a crew member of Expedition 64, and served as a station systems flight engineer.",
    },
    {
      key: 4,
      crewName: "Anousheh Ansari",
      role: "Flight Engineer",
      image: "/static/assets/crew/image-anousheh-ansari.png",
      content:
        "Anousheh Ansari is an Iranian American engineer and co-founder of Prodea Systems. Ansari was the fourth self-funded space tourist, the first self-funded woman to fly to the ISS, and the first Iranian in space. ",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Crew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[url('/static/assets/crew/background-crew-desktop.jpg')] bg-fixed bg-center bg-no-repeat bg-cover m-0">
        <Navbar />
        <div className="p-32 py-8">
          <p className="page-text font-normal text-[28px] text-white leading-[33.6px] tracking-[4.72px] uppercase">
            {" "}
            <span className="mr-6 font-bold text-white/25">02</span>
            Meet your crew
          </p>
          <Swiper
            // install Swiper modules
            modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
            spaceBetween={50}
            slidesPerView={1}
            autoplay={{
              delay: 3000,
            }}
            loop={true}
            pagination={{ clickable: true }}
            onSwiper={(swiper) => console.log(swiper)}
            onSlideChange={() => console.log("slide change")}
          >
            {crews.map((crew, i) => (
              <SwiperSlide>
                <div className="flex flex-row justify-evenly w-full">
                  <div className="basis-1/2 flex flex-row flex-wrap items-center">
                    <div className="crewPane">
                      <p className="font-normal leading[36.67px] text-white/[.5042] text-[32px] uppercase font-[Bellefair]">
                        {crew.role}
                      </p>
                      <p className="font-normal leading[64.18px] text-white text-[56px] uppercase font-[Bellefair]">
                        {crew.crewName}
                      </p>
                      <p className="font-normal text-[18px] leading-[32px] tracking-[4.72px] text-[#D0D6F9]">
                        {crew.content}
                      </p>
                    </div>
                  </div>
                  <div className="basis-1/2 flex row no-wrap justify-around items-end explore-button ">
                    <img src={crew.image} className="w-[453.44px] h-full" />
                  </div>
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </div>
    </div>
  );
}
