import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/molecules/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Space APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className="bg-[url('../public/static/assets/home/background-home-desktop.jpg')] bg-fixed bg-center bg-no-repeat bg-cover m-0">
        <Navbar />
        <div className='p-32'>
          {/* <Navbar /> */}
          <div className='flex flex-row justify-evenly w-full'>
            <div className='basis-1/2'>
              <p className='font-normal text-[28px] leading-[33.6px] tracking-[4.72px] text-[#D0D6F9] uppercase'>So, You want to travel to</p>
              <p className='font-normal leading[171.9px] text-white text-[150px] uppercase font-[Bellefair]'>Space</p>
              <p className='font-normal text-[18px] leading-[32px] tracking-[4.72px] text-[#D0D6F9]'>Let’s face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back, and relax because we’ll give you a truly out of this world experience!</p>
            </div>
            <div className='basis-1/2 flex row no-wrap justify-around items-end explore-button '>
              <div className='font-[Bellefair] text-[32px] font-normal leading-[36.67px] tracking-[2px] text-[#0B0D17] md:w-[274px] md:h-[274px] bg-white flex justify-center items-center text-center rounded-full cursor-pointer border-0 border-transparent outline-white/[0.1036] hover:outline hover:outline-[87px] hover:outline-white/[0.1036] hover:border-0 transition-all hover:transition-all hover:duration-[450ms] hover:ease-in-out'>
                Explore
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
